qutip/qutip-doc

changelog.rst

Although it has not actually been released, some of these changes could be quite important for some people to know, so here seems like the place for them.

Update changelog - CRAB and control evolution property name changes

---

guide/guide-states.rst

This PR contains work in progress towards #31.

Improved Guide section for superoperators and vectorization.

---

release_distribution.rst

This should be a reasonably comprehensive guide. Except that the 'Build documentation' section is empty, because I don't know what to put in it. Perhaps someone can pick that up later.
Mostly for now if people could check the 'Git workflow'. This is what I worked out from reading around, guess work and trial and error. It may be that there is a much easier workflow. I think the `cherry-pick` is necessary though, or something like it.

Instructions for creating, maintaining and distributing releases

---

changelog.rst

Some effort made to update it, but a lot of stuff that @nonhermitian added / merged not covered

Change log updated for v4 (partially)

---

installation.rst

Section on notes for Windows users also added
Some general small fixes also

build conda environment section added

---

conf.py

An error was occurring on latex build. Sphinx suggested this change

conf.py latex_keep_old_macro_names

---

guide/guide-random.rst

latexpdf should now build
It does!

Table Column definition fixed in guide-random

---

README.md
conf.py
installation.rst

Updates in building conda envs.
Removal of `sudo` from install from source.
Added developer install.
Adding section on installing on Windows with Python 2.7

V4.1 installation updates

---

changelog.rst

Adding the improvements for 4.3 release.

updating improvements for 4.3 release

---

apidoc/functions.rst

Docs nonmarkov

---

apidoc/functions.rst

Addressing #54, add to API doc in functions.rst:
- floquet_states, 
- floquet_master_equation_rates 
- floquet_collapse_operators 
- floquet_master_equation_tensor
- floquet_master_equation_steadystate
- floquet_basis_transform
- floquet_markov_mesolve

add some floquet functions

---

guide/guide-states.rst

Minimal additions to the guide corresponding to this PR on the main repo:
https://github.com/qutip/qutip/pull/998

Add short intro to quantum Hellinger distance

---

guide/guide-bloch.rst

closes https://github.com/qutip/qutip/issues/797

import numpy in doc example

---

apidoc/classes.rst
guide/dynamics/dynamics-options.rst
guide/dynamics/dynamics-photocurrent.rst
guide/dynamics/dynamics-stochastic.rst
guide/dynamics/dynamics-time.rst
guide/guide-dynamics.rst

Add documentation for stochastic code and updated some other part about solvers in general.

Stochastic

---

conf.py
guide/dynamics/dynamics-master.rst
guide/dynamics/dynamics-options.rst
guide/guide-basics.rst
guide/guide-bloch.rst
guide/guide-correlation.rst
guide/guide-overview.rst
guide/guide-random.rst

Those bugs already exist in the previously rendered version and somehow they are just neglected when building the doc (e.g http://qutip.org/docs/latest/guide/guide-random.html#). After the correction, those sections can be rendered, but there are still errors in other sections.

Fix some doc errors

---

guide/guide-visualization.rst

update user guide example of wigner_cmap

---

changelog.rst
guide/guide-bloch.rst

Added resolution argument in qutip to documentation, and created changelog fro 4.4.0

 added to changelog and documentation in guide-bloch

---

apidoc/classes.rst
gallery/qip/plot_qip_amplitude_noise.py
gallery/qip/plot_qip_intro_processor.py
gallery/qip/plot_qip_relaxation.py
guide/guide-qip.rst

Update from https://github.com/qutip/qutip/pull/1155.
I successfully rendered the doc by deleting some other files in the user guide. So the qip part and the gallery part should be fine. But there are still tons of old issues... They are mainly caused by wrong code in ipython code embedding. Use python embedding can solve it but needs some work...

update from control pulse PR

---

guide/guide-qip.rst

I wrote some example code for plotting a Quantum Circuit using the implemented QCircuit functionality.

Inserted section for plotting Quantum Circuits using QCircuit

---

CONTRIBUTING.md

It seems that ```source activate``` used to be an older version of ```conda activate```. (line 61)

Changed ```source activate``` to ```conda activate```

---

development/ideas/tensorflow-data-backend.rst

This is a small PR to address the typos and such found after #133 was merged.

Fix typos and grammatical errors in TensorFlow proposal.

---

installation.rst

Updates broken links in `Installation` page of documentation.

Fixes broken links in docs
